### ISSUE TITLE
Position problem with FontAwesome icon animation

### ISSUE THREAD

**Issue by ljevarster** [IanLunn/Hover#52]
Hi beautiful script! Thank you!

I'm using fontAwesome icons on my site + I'm using hover.css.

Now if you navigate to my website: www.jedanaest.com.hr and scroll all the way down to the footer area, you will see a contact widget with super cool icons that are animated on hover.

The only problem I have is that I want the icon to be first i.e. on the left, and then text.

Is this something I need to do with CSS or is it a HTML problem? The problem does not persist if I use a non-icon animation, but the bot text and icon animate.

Thanks!

**Comment by IanLunn** [comment]
You need to make two changes to the CSS. Taking `icon-wobble-vertical` as an example, you need to change `padding-right: 2.2em` to `padding-left: 2.2em`:

```css
.hvr-icon-wobble-vertical {
  display: inline-block;
  vertical-align: middle;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
  box-shadow: 0 0 1px rgba(0, 0, 0, 0);
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  -moz-osx-font-smoothing: grayscale;
  position: relative;
  padding-right: 2.2em;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
}
```

and change `right: 1em` to `left: 1em`:

```css
.hvr-icon-wobble-vertical:before {
  content: "\f062";
  position: absolute;
  right: 1em;
  padding: 0 1px;
  font-family: FontAwesome;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
}
```
