### ISSUE TITLE
Add left border reveal and right border reveal

### ISSUE THREAD

**Issue by LJNielsenDk** [IanLunn/Hover#86]

**Comment by mathielen** [comment]
Check this

```scss
@mixin leftline-reveal {
  $duration: $mediumDuration;

  @include hacks();
  position: relative;
  overflow: hidden;

  &:before {
    content: "";
    position: absolute;
    z-index: -1;
    left: 0;
    right: 0;
    top: 0;
    height: 100%;
    background: $activeColor;
    width: 4px;
    @include prefixed(transform, translateX(-4px));
    @include prefixed(transition-property, transform);
    @include prefixed(transition-duration, $duration);
    @include prefixed(transition-timing-function, ease-out);
  }

  &:hover,
  &:focus,
  &:active {

    &:before {
      @include prefixed(transform, translateX(0));
    }
  }
}
```
